### ISSUE TITLE
Create a module for Proxy API Gateway plus lamba

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/terraform-modules#17]
We should build a module that deploys an API gateway in proxy mode and pushes all the traffic into a lambda - something like this (https://github.com/cds-snc/scan-websites/tree/main/terragrunt/aws/api) with more features. Ex:

- Route 53 integration
- SSL certs
- Healthchecks

**Comment by sylviamclaughlin** [comment]
@maxneuvians - is this still a thing? The reason I am asking is because I remember Pat saying that we are moving away from an API gateway and instead using lambda function urls. I was going to pick up this ticket, but wanted to make sure if it is still needed. Thanks!

**Comment by maxneuvians** [comment]
No longer needed
